pub mod about;
pub mod appearance;
pub mod editor;
pub mod files;
pub mod keyboard;
pub mod lsp;
pub mod scm;
pub mod search;
pub mod workbench;

pub use about::*;
pub use appearance::*;
pub use editor::*;
pub use files::*;
pub use keyboard::*;
pub use lsp::*;
pub use scm::*;
pub use search::*;
pub use workbench::*;
